### ISSUE TITLE
Unable to run the code on Windows platform

### ISSUE THREAD

**Issue by rhavinal** [archjeb/pfctest#2]
This is pretty good handy tool. But I am unable to run this on Windows 2016 with python 3.6.4 version. 

Get the below error message. Does it only run on Linux ? 

C:\Users\Administrator\Desktop\pfctest-master>pfctest.py -d leaf1 --p 6 -i 100
  File "C:\Users\Administrator\Desktop\pfctest-master\pfctest.py", line 112
    print os.path.basename(sys.argv[0]), "  Version: ", VERSION
           ^
SyntaxError: invalid syntax

C:\Users\Administrator\Desktop\pfctest-master> 

Rgds,
Raghu

**Comment by archjeb** [comment]
Hello,

You have two issues:

1. This does not support Python 3, only 2.6 & 2.7 and you are running Python 3.6.4 version. The print statements need to be converted to functions.

2. Unfortunately, Windows doesn't support Raw sockets and AF_PACKET sockets. You'll need to use Linux platform for this.

-J

**Comment by rhavinal** [comment]
Thanks for your quick response. Wish we had something similar on Windows too.

Thanks,
Raghu
