### ISSUE TITLE
please add padding

### ISSUE THREAD

**Issue by SarathBug** [archjeb/pfctest#3]
https://github.com/archjeb/pfctest/blob/dccf25b5f7291ef52bb8a20c17b3e81707079053/pfctest.py#L284

Thanks for the script. 

28byte padding is required is so that it meets the min frame length requirements

**Comment by archjeb** [comment]
Sorry for the delay on this. Added padding so that we are at 60bytes...plus the 4byte FCS for 64byte total frame size.
